### ISSUE TITLE
How to refresh token ?

### ISSUE THREAD

**Issue by Incremental92** [rluders/oc-jwtauth-plugin#54] opened 2021-01-17 23:05 UTC
Ahoj Ricardo,
I'm trying to refresh the token in Vue.js with the following script
`   refreshToken ({ commit }) {
      const authorization = { headers: { 'Authorization': 'Bearer ' + state.token } }
      this.$axios
         .patch(SERVER_URL + "/api/auth/refresh-token", authorization)
         .then(response => { }
`
I get first an HTTP 200, then an HTTP 404 and finally a CORS error "Network Error"

Could it be the same as issue  https://github.com/rluders/oc-jwtauth-plugin/issues/49 ?

![image](https://user-images.githubusercontent.com/63950081/104858606-ca224080-5920-11eb-9672-00c64b64bb16.png)

**Comment by rluders** [comment] 2021-01-22 14:04
You are getting these errors 'cause of the CORS issue. I'll work on a solution this weekend. :)

**Comment by rluders** [comment] 2021-01-23 20:41
It should be fixed once you update the CORS plugin.

**Comment by Incremental92** [comment] 2021-01-23 22:29
Ricardo, the version in OctoberCMS stick to 1.0.3
I can't update to 1.0.5 !
Should it be done manually ?

**Comment by rluders** [comment] 2021-01-23 22:51
Oh. It is probably cause I decided to make the version that is installed from the Marketplace to be paid.

So, if you want to keep using it from the marketplace, you need to buy it. It is the way that I found to help me keep working on it, and also helping the OctoberCMS to get part of the money. Benefits from buying is that you get the easy install and auto update functionality. 

Otherwise, you can install it directly from the github if you want. 'Cause it still free if you install direct from the repository, not using the OctoberCMS Marketplace.

**Comment by Incremental92** [comment] 2021-01-23 22:52
Yes, but I mean the CORS plugin. It still free ?

**Comment by rluders** [comment] 2021-01-23 23:01
Ops, sorry. I'm almost sleeping here.

Yes. It still free to be installed by the marketplace. It didn't get
updated there yet? Maybe I need to trigger something manually to release
the new version.

**Comment by rluders** [comment] 2021-01-23 23:04
Yeah. I seem that the Marketplace didn't automatically trigger the version release. So, I did it manually, you should be able to update it from the CMS administration right now.

**Comment by Incremental92** [comment] 2021-01-24 10:21
Hello Ricardo, I updated succesfully the CORS now, but I'm not able to login now.
I get the following error from October :
![image](https://user-images.githubusercontent.com/63950081/105627274-3e377980-5e36-11eb-8318-754df2489c91.png)

**Comment by rluders** [comment] 2021-01-24 11:46
Looks like it didn't downloaded the dependencies for some reason. Can I
recommend you to uninstall the plug-in and install it again?

**Comment by Incremental92** [comment] 2021-01-24 11:54
I uninstalled CORS and reinstalled, but I get the same error.

**Comment by rluders** [comment] 2021-01-24 12:20
Okay . Let me check it.

**Comment by rluders** [comment] 2021-01-24 14:15
@Incremental92 it seems that the OctoberCMS isn't installing the dependencies. Which method did you use to install the OctoberCMS? Composer?

**Comment by Incremental92** [comment] 2021-01-24 14:23
Well, I'm developping on W10 with WinNMP and I installed October with the official installer : install-master.zip

**Comment by rluders** [comment] 2021-01-24 14:40
Not sure what is causing it. But there is a working around that you can do.

> Note: I do recommend you make a FULL PROJECT BACKUP before executing the following steps. :)

1. Download [this composer.json file](https://github.com/rluders/oc-cors-plugin/blob/main/composer.json)
2. Copy the file to the plugin folder: `<myoctobercms>/plugins/rluders/cors`
3. Then download [this composer.json file](https://github.com/octobercms/october/blob/develop/composer.json)
4. Copy the file to the OctoberCMS root folder.
5. Edit your `<myoctobercms>/config/cms.php` and change the `disableCoreUpdates` to `true`.
6. Open a terminal from your OctoberCMS root folder and execute the command: `composer update`

It should install the plugin dependencies. I'm not sure why it is not installing it by default, I'm wondering if it is not a bug related to the OctoberCMS.

**Comment by Incremental92** [comment] 2021-01-24 14:47
Thanks, I will try.
But I don't really understand the problem. Is it a declaration not resolved in your plugin and do you think there's a workaround to do in your plugin ?
Otherwise could a bug be opened on the October project ?

**Comment by rluders** [comment] 2021-01-24 14:51
I'm not sure. I thibk that it could be a isos at the OctoberCMS, but I need
to check.

Probably by installing any other plug-in that depends on composer to manage
its dependencies will give some idea about what is happening.

But today I'm done. Maybe tomorrow I'll have some time to work on it.

**Comment by Incremental92** [comment] 2021-01-24 15:01
I got these errors :
Loading composer repositories with package information
**Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2**
Updating dependencies (including require-dev)

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 134217736 bytes) in phar://C:/Dev/WinNMP/bin/composer/composer.phar/src/Composer/DependencyResolver/RuleSet.php on line 84

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

**Comment by Incremental92** [comment] 2021-01-24 15:11
OK, I updated composer to V2 and restarted composer update.
_If this can help, I had a long update with  :_
The "wikimedia/composer-merge-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 100 installs, 0 updates, 0 removals
....

_Then ending with :_

75 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files

  **[RuntimeException]
  Could not scan for classes inside "tests/concerns/InteractsWithAuthentication.php" which does not appear to be a file nor a folder**


update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by Incremental92** [comment] 2021-01-24 15:12
It didn't solved, I still can't log in my app

**Comment by Incremental92** [comment] 2021-01-24 15:17
In fact, the server was crashed with the following error for backend and frontend :
Warning: require(): Invalid date.timezone value 'UTC+2', we selected the timezone 'UTC' for now. in C:\Dev\WinNMP\WWW\Meteo\vendor\composer\autoload_real.php on line 66

Warning: require(C:\Dev\WinNMP\WWW\Meteo\vendor\composer/../symfony/polyfill-php70/bootstrap.php): failed to open stream: No such file or directory in C:\Dev\WinNMP\WWW\Meteo\vendor\composer\autoload_real.php on line 66

Warning: require(): Invalid date.timezone value 'UTC+2', we selected the timezone 'UTC' for now. in C:\Dev\WinNMP\WWW\Meteo\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'C:\Dev\WinNMP\WWW\Meteo\vendor\composer/../symfony/polyfill-php70/bootstrap.php' (include_path='.;c:/dev/winnmp/include') in C:\Dev\WinNMP\WWW\Meteo\vendor\composer\autoload_real.php on line 66

I restored the backup !

**Comment by rluders** [comment] 2021-01-25 08:52
Let's move the issue to the CORS repository, since it is related to that plugin and not really about the JWTAuth plugin. Closing this issue here.

https://github.com/rluders/oc-cors-plugin/issues/5

**Closed by rluders** 2021-01-25 08:52 UTC
Labels: not a bug, support
